[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "D6egLe5YR6rMMsviwvuP2vS1MbtxPFLaGC27Rb9z2Eaw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
